import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'index', label: 'Welcome to Adri AI Docs'},
    {type: 'doc', id: 'use-adri-for-free', label: 'Use Adri for Free'},
    {
      type: 'category',
      label: 'Project Management',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'project-management'}],
    },
    {
      type: 'category',
      label: 'Connect SAP System',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'connect-sap-system'}],
    },
    {
      type: 'category',
      label: 'Adri AI Foundry for VS Code',
      collapsed: false,
      items: [
        'vs-code-extension/introduction',
        'vs-code-extension/install-vs-code-extension',
        'vs-code-extension/open-folder-in-vs-code',
        'vs-code-extension/sign-in-adri-ai',
        'vs-code-extension/connect-to-a-system',
        'vs-code-extension/disconnect-a-system',
        'vs-code-extension/vpn-users',
        'vs-code-extension/download-resources',
        'vs-code-extension/install-mcp-for-claude-code',
        'vs-code-extension/install-mcp-for-codex',
        'vs-code-extension/abap-debugger',
      ],
    },
    {
      type: 'category',
      label: 'AI Providers',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ai-providers'}],
    },
    {
      type: 'category',
      label: 'Agent Booster Setup',
      collapsed: false,
      items: [
        'adri-mcp-server/agent-booster-setup',
        'adri-mcp-server/setup-enabler-framework',
        'adri-mcp-server/setup-img-extraction',
      ],
    },
    {
      type: 'category',
      label: 'Adri MCP Server',
      collapsed: false,
      items: [
        'adri-mcp-server/install-tools-for-mcp',
        'adri-mcp-server/setup-in-claude-code',
        'adri-mcp-server/setup-in-codex',
        'adri-mcp-server/add-as-claude-connector',
        'adri-mcp-server/authenticate-using-token',
        'adri-mcp-server/connect-ibm-bob',
        'adri-mcp-server/mcp-capabilities',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'use-cases'}],
    },
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'case-studies'}],
    },
    {
      type: 'category',
      label: 'Capabilities',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'capabilities'}],
    },
    {
      type: 'category',
      label: 'Code Agent',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'code-agent'}],
    },
    {
      type: 'category',
      label: 'SAP Research Agent',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'research-agent'}],
    },
    {
      type: 'category',
      label: 'Deploying Adri in Enterprise',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'enterprise-deployment'}],
    },
    {
      type: 'category',
      label: 'AI Concepts',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'ai-concepts'}],
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'glossary'}],
    },
    {
      type: 'category',
      label: 'Comparisons',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'comparisons'}],
    },
    {type: 'doc', id: 'faqs'},
    {type: 'doc', id: 'contact'},
  ],
};

export default sidebars;
